### ISSUE TITLE
Discrepancy in MARS query and gallery split

### ISSUE THREAD

**Issue by InnovArul** [liangzheng06/MARS-evaluation#4]
Hi,

I came across this: https://github.com/jiyanggao/Video-Person-ReID/issues/6
It seems that in the split given in this repo, there are some Query identities that is not having matching instances in Gallery. Does this mean, the algorithms should have **'not in the gallery'** classification too? As far as I know, the query identities will always be present in the Gallery while performing test (as per current literature papers).

code to find the bug: https://gist.github.com/InnovArul/1992c75d746b0700311976b4a3d128ea

could you please clarify regarding this?

**Comment by dpernes** [comment]
Did you figure out the issue?

Moreover, I think there is an inconsistency between the given query/gallery split and what is written in the   [dataset paper](http://www.liangzheng.com.cn/1320.pdf). At the beginning of section "3.2 Evaluation Protocol", it is stated that (my bold):

> In the MARS dataset, we stick to the cross-camera search mode as in previous
datasets [12, 23, 43], i.e., **query and gallery are captured by different cameras**.

However, this is not true for the given query/gallery split, since we have samples from all cameras 1 to 6 in both query and gallery sets... Should we do something about it?

**Comment by InnovArul** [comment]
> In the MARS dataset, we stick to the cross-camera search mode as in previous
datasets [12, 23, 43], i.e., query and gallery are captured by different cameras.

I didn't look into the paper. Thanks for pointing out. I have verified this point as well (updated the gist) that query and gallery are from overlapping cameras for same identity.

So far, I haven't figured out the solution or workaround for the issue. I have dropped a mail to the author as well and I haven't heard back. Regarding non-overlapping query and gallery PIDs, it is found that only 28 query instances are affected by this out of 1980. Hence, the maximum rank-1 performance possible in MARS dataset is 98.585 %.

**Comment by percarlsen** [comment]
It actually seems like the authors have the query labels included in the gallery, which contradicts the description of the evaluation protocol in the paper. From test_mars.m: 
line 14: `track_test = importdata('info/tracks_test_info.mat');`
line 30: `label_gallery = track_test(:, 3);`
line 31: `label_query = label_gallery(query_IDX);`
`label_gallery` is then used without removing the query labels (at least as far as I can tell).

While inspecting some of the labels you found not to be in the gallery (ID: [6, 152, 436, 454, 640, ...]), I noticed that they all only consist of two video sequences captured by different cameras. 

From the paper:

> Each identity will have one probe under each camera

Thus, since these person IDs only have one video sequence pr. camera, removing the query sequences from the gallery essentially removes all data associated with these persons from the gallery.

To make comparisons fair I guess one would just have to keep the query data in the gallery.

**Comment by InnovArul** [comment]
if you look at the code here https://github.com/liangzheng06/MARS-evaluation/blob/master/utils/evaluation_mars.m#L11-L18, they are actually adding the query data to junk, which will make sure to not to include query when calculating numbers (rankX accuracy and precision).

**Comment by percarlsen** [comment]
Ah thanks for pointing that out. Did you hear back from the authors?

**Comment by liangzheng06** [comment]
> > In the MARS dataset, we stick to the cross-camera search mode as in previous
> > datasets [12, 23, 43], i.e., query and gallery are captured by different cameras.
> 
> I didn't look into the paper. Thanks for pointing out. I have verified this point as well (updated the gist) that query and gallery are from overlapping cameras for same identity.
> 
> So far, I haven't figured out the solution or workaround for the issue. I have dropped a mail to the author as well and I haven't heard back. Regarding non-overlapping query and gallery PIDs, it is found that only 28 query instances are affected by this out of 1980. Hence, the maximum rank-1 performance possible in MARS dataset is 98.585 %.

Hi, sorry for the late response. 
There might be some cases like you described. Yet, for fair comparisons with others, I suggest that you use the standard evaluation protocol, leaving those problematic ones to 0 if there is no matching images. Like you pointed out, leaving those items to 0 does not significantly affect result. Just to make sure it is fair for every one.

**Comment by InnovArul** [comment]
@liangzheng06 Thanks a lot for the reply, as well as the dataset! 

I am not sure what you meant by "leaving those problematic ones to 0".
Just to be clear that I understand correctly, you are suggesting to accept that some query instances will not have a corresponding gallery instance. I believe, that's the evaluation procedure carried out so far by everyone.  Hence, the maximum rank-1 performance that can be achieved in MARS dataset is 98.585 % (leaving out those 28 query instances without corresponding gallery instance). 

Is my understanding correct?

**Comment by liangzheng06** [comment]
yes, your understanding is correct.

?? Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by InnovArul** [comment]
Based on dataset author's (@liangzheng06), closing the issue.
